export const ROUTES = {
  landing: "/",
  login: "/login",
  register: "/register",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  onboardingWelcome: "/onboarding/welcome",
  onboardingMeq: "/onboarding/meq",
  onboardingObligations: "/onboarding/obligations",
  onboardingReview: "/onboarding/review",
  dashboard: "/dashboard",
  plan: "/plan",
  tracking: "/tracking",
  trackingHistory: "/tracking/history",
  education: "/education",
  faq: "/education/faq",
  events: "/events",
  settings: "/settings",
  privacy: "/privacy",
  terms: "/terms",
} as const;
